package generator

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"github.com/tomasbasham/ciphersuites/internal/domain"
)

// CodeGenerator produces Go source code from cipher suite data.
type CodeGenerator struct {
	packageName string
	sourceURL   string
	template    *template.Template
}

// NewCodeGenerator creates a new code generator.
func NewCodeGenerator(packageName, sourceURL string) *CodeGenerator {
	tmpl := template.Must(template.New("ciphersuites").Parse(codeTemplate))

	return &CodeGenerator{
		packageName: packageName,
		sourceURL:   sourceURL,
		template:    tmpl,
	}
}

// Generate produces Go source code from grouped cipher suites.
func (g *CodeGenerator) Generate(grouped map[domain.SecurityLevel][]domain.CipherSuite) ([]byte, error) {
	orderedLevels := []domain.SecurityLevel{
		domain.Recommended,
		domain.Secure,
		domain.Weak,
		domain.Insecure,
	}

	var securityLevels []SecurityLevelGroup
	for _, level := range orderedLevels {
		if suites, exists := grouped[level]; exists && len(suites) > 0 {
			description := strings.ToLower(string(level)) + " cipher suites"
			if level == domain.Recommended {
				description = "secure cipher suites recommended for\n// use"
			}

			securityLevels = append(securityLevels, SecurityLevelGroup{
				Name:        string(level),
				Description: description,
				Suites:      suites,
			})
		}
	}

	data := TemplateData{
		PackageName:    g.packageName,
		Timestamp:      time.Now().UTC().Format(time.RFC3339),
		SourceURL:      g.sourceURL,
		SecurityLevels: securityLevels,
	}

	var buf bytes.Buffer
	if err := g.template.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("template execution failed: %w", err)
	}

	return buf.Bytes(), nil
}

// TemplateData contains the data for code generation.
type TemplateData struct {
	PackageName    string
	Timestamp      string
	SourceURL      string
	SecurityLevels []SecurityLevelGroup
}

// SecurityLevelGroup represents a group of cipher suites at the same security
// level.
type SecurityLevelGroup struct {
	Name        string
	Description string
	Suites      []domain.CipherSuite
}

const codeTemplate = `// Code generated by cipher suite generator. DO NOT EDIT.
// Generated at: {{.Timestamp}}
// Source: {{.SourceURL}}

package {{.PackageName}}

{{range .SecurityLevels}}
// {{.Name}}CipherSuites is a list of {{.Description}}.
var {{.Name}}CipherSuites = map[string]CipherSuite{
{{range .Suites}}	"{{.Name}}": {"{{.Protocol}}", "{{.Encryption}}", "{{.Hash}}", {{.Security}}, []string{ {{range $i, $v := .TLSVersions}}{{if $i}}, {{end}}"{{$v}}"{{end}} }},
{{end}}}

{{end}}`
